update products_services_types set products_services_type_old_id = 'DBT' where products_services_description = 'Debit';
update products_services_types set products_services_type_old_id = 'BC' where products_services_description = 'Bankcard';
update products_services_types set products_services_type_old_id = 'GIFT' where products_services_description = 'Gift & Loyalty';
update products_services_types set products_services_type_old_id = 'CG' where products_services_description = 'Check Guarantee';
update products_services_types set products_services_type_old_id = 'VC' where products_services_description = 'Virtual Check';
update products_services_types set products_services_type_old_id = 'EBT' where products_services_description = 'EBT';
update products_services_types set products_services_type_old_id = 'VCWEB' where products_services_description = 'Virtual Check Web-based';
update products_services_types set products_services_type_old_id = 'TE' where products_services_description = 'T&E';
update products_services_types set products_services_type_old_id = 'AF' where products_services_description = 'Annual Fee';
update products_services_types set products_services_type_old_id = 'DISC' where products_services_description = 'Discover';
update products_services_types set products_services_type_old_id = 'AMEX' where products_services_description = 'American Express';
update products_services_types set products_services_type_old_id = 'GW' where products_services_description = 'USA ePay';
update products_services_types set products_services_type_old_id = 'GW1' where products_services_description = 'Gateway 1';
update products_services_types set products_services_type_old_id = 'GW2' where products_services_description = 'Gateway 2';
update products_services_types set products_services_type_old_id = 'HZ' where products_services_description = 'Hooza';
update products_services_types set products_services_type_old_id = 'ACHP' where products_services_description = 'ACH';
update products_services_types set products_services_type_old_id = 'AUTH' where products_services_description = 'Authorize.net';
update products_services_types set products_services_type_old_id = 'TG' where products_services_description = 'TGate';
update products_services_types set products_services_type_old_id = 'WP' where products_services_description = 'WebPASS';