version: 2.1

jobs:
  build:
    docker:
      - image: cimg/php:8.1.5
    steps:
      - checkout
      - run:
          name: Install packages
          command: |
            php --version

workflows:
  build:
    jobs:
      - build
