version: 2.1

phpimg: &phpimg
  docker:
    - image: cimg/php:7.4.26
      environment:
        TEST_DATABASE_URL: postgresql://axiauser:aXiadb123@localhost/axiadb
        POSTGRES_USER: axiauser
        POSTGRES_DB: axiadb
        POSTGRES_PASSWORD: aXiadb!123

    - image: cimg/postgres:14.0
      environment:
        POSTGRES_USER: axiauser
        POSTGRES_DB: axiadb
        POSTGRES_PASSWORD: aXiadb!123
jobs:
  build:
    <<: *phpimg

    steps:
      - checkout
      - run:
          name: Install packages
          command: |
            php --version

  prepare:
    <<: *phpimg


    steps:
      - checkout
      - run:
          name: prepare
          command: |
            mkdir test1
            mkdir test1/test2
            touch test1/test2/file1.txt
            echo Persisted to workspace > test1/test2/file1.txt
            mkdir myspace
            mkdir myspace/space1
            echo Is the file persisted > myspace/space1/test.txt
            ls -al
      - persist_to_workspace:
          root: ~/
          paths: "*"


  lint:
    <<: *phpimg

    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: Lint
          command: |
            ls -al
            ls -al myspace
            ls -al myspace/space1
            ls -al test1
            ls -al test1/test2
            cat test1/test2/file1.txt
            php -l --exclude='Vendor,Plugin,vendor,Lib,Locale,tmp,*.php' app
            # echo "run lint"
  

  phploc:
    <<: *phpimg

    steps:
      - checkout
      - run:
          name: phploc
          command: |
            sudo apt-get update
            sudo apt-get install phploc
            # wget https://phar.phpunit.de/phploc.phar
            wget -O phive.phar "https://phar.io/releases/phive.phar"
            wget -O phive.phar.asc "https://phar.io/releases/phive.phar.asc"
            gpg --keyserver hkps://keys.openpgp.org --recv-keys 0x6AF725270AB81E04D79442549D8A98B29B2D5D79
            gpg --verify phive.phar.asc phive.phar
            rm phive.phar.asc
            chmod +x phive.phar
            sudo mv phive.phar /usr/local/bin/phive
            echo GOT HERE-------------------------
            echo y | phive install phploc
            echo PASSSSSS--------------------
            phploc --version
            # # bash -c phploc --log-csv build/logs/phploc.csv app
            # ./phploc --log-csv build/logs/phploc.csv app
            # # echo "Run phploc"
     
  pdepend:
    <<: *phpimg

    steps:
      - checkout
      - run:
          name: pdepend
          command: |
            echo PASSSSS------------------------------SsSSSSSSSSSSSSSSSSSSSSSSSSS
            bash -c pdepend --summary-xml=build/pdepend/summary.xml -jdepend-chart=build/pdepend/dependencies.svg --overview-pyramid=build/pdepend/overview-pyramid.svg --jdepend-xml=build/logs/jdepend.xml --ignore=Console,Locale,Plugin,vendor,Vendor app
            echo  "Run pdepend"

  phpmd-ci:
    <<: *phpimg

    steps:
    - checkout
    - run:
        name: phpmd-ci
        command: |
          sudo apt-get update
          echo PASSSSS------------------------------SsSSSSSSSSSSSSSSSSSSSSSSSSS
          bash -c phpmd app xml codesize,unusedcode,naming --exclude 'Console,Plugin,tmp,vendor,Vendor' --reportfile build/logs/phpmd.xml
          echo "Run phpmd-ci"

  phpcs:
    <<: *phpimg
    
    steps:
      - checkout
      - run:
          name: phpcs
          command: |
            phpcs -v -n --standard=CakePHP --report=summary --ignore=Console,Plugin,tmp,vendor,Vendor,webroot,.css,.js app
            echo "Run phpcs"

  phpcs-ci:
    <<: *phpimg

    steps:
      - checkout
      - run:
          name: phpcs-ci
          command: |
            # bash -c phpcs -n --standard=CakePHP --ignore=Console,Plugin,tmp,Test,vendor,Vendor,webroot,.css,.js --report-full=build/logs/phpcs_full.txt app
            echo "Run phpcs-ci"
      
  phpcpd:
    <<: *phpimg

    steps:
      - checkout

      - run:
          name: phpcpd
          command: |
            sudo apt-get update
            sudo apt-get install phpcpd
            echo PASSSSS------------------------------SsSSSSSSSSSSSSSSSSSSSSSSSSS
            phpcpd --progress --exclude='Vendor,Plugin,vendor' --log-pmd build/logs/pmd-cpd.xml app
            echo "Run phpcpd"

  phpdox:
    <<: *phpimg

    steps:
      - checkout

      - run:
          name: phpdox
          command: |
            sudo apt-get update
            sudo apt-get install phpdox
            echo PASSSSS------------------------------SsSSSSSSSSSSSSSSSSSSSSSSSSS
            phpdox -f phpdox.xml.dist
            echo "Run phpdox"

  phpunit:
    <<: *phpimg

    steps:
      - checkout

      - run:
          name: phpunit
          command: |
            # bash -c Console/cake DbTest.db_test --stderr --testdox --log-junit '../build/reports/junit.xml' --coverage-html webroot/coverage --coverage-clover '../build/reports/coverage-clover.xml' --configuration '../phpunit.xml' app AllTests
            echo "Run phpunit"
  phpcb:
    <<: *phpimg

    steps:
      - checkout

      - run:
          name: ensure-tmp-folders
          command: |
            mkdir -p app/tmp/{logs,tests,sessions,cache}
            mkdir app/tmp/cache/{persistent,models,views}

      - run:
          name: phpcb
          command: |
            # bash -c phpcb --log build/logs --source app --output app/webroot/code-browser --ignore 'app/Pluging,app/tmp,app/vendor,app/Vendor'
            echo "Run phpcb"

workflows:
  build:
    jobs:
      - build
      - prepare
      - pdepend:
          requires: [ prepare ]
      - phpmd-ci:
          requires: [ prepare, pdepend ]
      - lint:
          requires: [ prepare ]
      - phpcpd
      - phpcs-ci
      - phploc
      - phpdox